name: docker

on:
  push:
    branches: [ master ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        run: |
          docker build -t 4pdosc/ai-benchmark:2.4.1-gpu .
          docker push 4pdosc/ai-benchmark:2.4.1-gpu
